#!/usr/bin/env python3
"""Generate ``docs/api_reference.md`` from the ``seabornmasterpro`` docstrings.

Run ``python scripts/build_api_reference.py`` after changing a public signature or
docstring. The output is deterministic so it can be diffed in review.
"""

from __future__ import annotations

import importlib
import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

MODULES = ["theme", "io", "stats", "annotate", "color", "layout", "repro", "datasets", "benchmark"]
OUT = ROOT / "docs" / "api_reference.md"


def _signature(obj: object) -> str:
    try:
        return str(inspect.signature(obj))  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return "(...)"


def _doc(obj: object) -> str:
    return inspect.getdoc(obj) or "*No docstring.*"


def _render_member(name: str, obj: object) -> list[str]:
    lines: list[str] = []
    if inspect.isclass(obj):
        lines.append(f"### `{name}`\n")
        lines.append(_doc(obj) + "\n")
        fields = getattr(obj, "__dataclass_fields__", None)
        if fields:
            lines.append("| Field | Type |\n|---|---|")
            for fname, f in fields.items():
                ftype = getattr(f.type, "__name__", str(f.type))
                lines.append(f"| `{fname}` | `{ftype}` |")
            lines.append("")
        for mname, member in inspect.getmembers(obj):
            if mname.startswith("_") or not (
                inspect.isfunction(member) or isinstance(member, property)
            ):
                continue
            target = member.fget if isinstance(member, property) else member
            kind = "property" if isinstance(member, property) else "method"
            lines.append(
                f"- **`{mname}{'' if kind == 'property' else _signature(target)}`** ({kind}) — {_doc(target).splitlines()[0]}"
            )
        lines.append("")
    elif inspect.isfunction(obj):
        lines.append(f"### `{name}{_signature(obj)}`\n")
        lines.append(_doc(obj) + "\n")
    else:
        lines.append(f"### `{name}`\n")
        lines.append(f"Constant of type `{type(obj).__name__}`.\n")
    return lines


def build() -> str:
    pkg = importlib.import_module("seabornmasterpro")
    out = [
        "# 📚 API Reference",
        "",
        f"`seabornmasterpro` {pkg.__version__}. Generated by `scripts/build_api_reference.py`; do not edit by hand.",
        "",
        "The most common helpers are re-exported at the top level:",
        "",
        "```python",
        "import seabornmasterpro as smp",
        "smp.apply_theme(); smp.set_seed(0); smp.compare_groups(df, 'group', 'value')",
        "```",
        "",
        "## Modules",
        "",
    ]
    for mod_name in MODULES:
        out.append(f"- [`seabornmasterpro.{mod_name}`](#seabornmasterpro{mod_name})")
    out.append("")
    for mod_name in MODULES:
        mod = importlib.import_module(f"seabornmasterpro.{mod_name}")
        out.append(f"## `seabornmasterpro.{mod_name}`")
        out.append("")
        out.append(_doc(mod))
        out.append("")
        names = list(getattr(mod, "__all__", []))
        for name in names:
            obj = getattr(mod, name)
            out.extend(_render_member(name, obj))
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    text = build()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is out of date; run scripts/build_api_reference.py", file=sys.stderr)
            return 1
        print("api_reference.md is up to date")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
